--- src/Makefile	2020-04-24 16:18:56.000000000 +0200
+++ src/Makefile	2020-07-13 17:24:10.598638204 +0200
@@ -3,7 +3,7 @@
 WARNINGS=-Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Werror
 #WARNINGS=-Wunreachable-code 	# Gcc 4.1 .. 4.4 are too buggy to make this useful
 
-LIBDIR ?= /lib/security
+LIBDIR ?= /usr/lib/security
 
 build: pam_python.c setup.py Makefile
 	@[ ! -e build -o build/lib.*/pam_python.*.so -nt setup.py -a build/lib.*/pam_python.so -nt Makefile ] || rm -r build
@@ -15,8 +15,8 @@
 .PHONY: install install-lib
 install: install-lib
 install-lib:
-	s=$$([ $$(id -u) = 0 ] || echo sudo); $$s mkdir -p $(DESTDIR)$(LIBDIR)
-	s=$$([ $$(id -u) = 0 ] || echo sudo); $$s cp build/lib.*/pam_python*.so $(DESTDIR)$(LIBDIR)
+	s=$$([ $$(id -u) = 1000 ] || echo sudo); $$s mkdir -p $(DESTDIR)$(LIBDIR)
+	s=$$([ $$(id -u) = 1000 ] || echo sudo); $$s cp pam_python.so $(DESTDIR)$(LIBDIR)
 
 .PHONY: clean
 clean:
@@ -26,7 +26,7 @@
 
 .PHONY: ctest
 ctest:	ctest.c Makefile
-	gcc -O0 $(WARNINGS) -g -o $@ ctest.c -lpam -lpython3.6m
+	gcc -O0 $(WARNINGS) -g -o $@ ctest.c -lpam -lpython3.8
 
 test-pam_python.pam: test-pam_python.pam.in Makefile
 	sed "s,\\\$$PWD,$$(pwd),g" "$@.in" >"$@.tmp"
